const LAST_UPDATED="4 oktober 2026 • 21:07 CEST";
const EVENTS=[
{id:"ukmto-151",publishedAt:"2026-10-04T21:07:00+02:00",date:"4 okt 2026 • 21:07 CEST Reuters",type:"attack",status:"confirmed",statusLabel:"UKMTO 151-26",title:"Flera explosioner nära tanker söder om Al Mukha",coords:[12.85,43.35],summary:"En tanker rapporterade flera explosioner i nära anslutning cirka 60 nautiska mil söder om Al Mukha i Jemen. Besättningen rapporterades säker och ingen miljöpåverkan rapporterades. Myndigheter utreder och ansvarig aktör är inte fastställd.",impact:"Ökad säkerhetsrisk även vid Bab el-Mandeb/Gulf of Aden kan förstärka omdirigeringar och ton-mile-efterfrågan, vilket stödjer tankerfrakt men höjer operativ risk och försäkringskostnader.",stock:{"at":"$87.28 (senaste avslut 2 okt • NYSE stängd)","h1":"Ingen handel","close":"$87.28 (2 okt)","h24":"Inväntar nästa handelsdag"},source:"https://www.ukmto.org/",latest:true},
{id:"iran-conditions",publishedAt:"2026-10-04T09:59:00+02:00",date:"4 okt 2026",type:"policy",status:"confirmed",statusLabel:"BEKRÄFTAT",title:"Iran knyter full återöppning till sju villkor",coords:[26.55,56.25],summary:"Irans talman säger att sundet inte öppnas fullt förrän USA uppfyller villkoren i Islamabad-överenskommelsen. Reuters rapporterar att tvisten gäller ordningsföljden i genomförandet.",impact:"Stödjer en längre period av logistisk friktion och riskpremie; ett avtal kan däremot snabbt pressa rater.",stock:{"at":"$87.28 (senaste avslut 2 okt)","h1":"Ingen handel","close":"$87.28 (2 okt)","h24":"Inväntar 5 okt"},source:"https://www.reuters.com/world/middle-east/iran-says-strait-hormuz-will-not-reopen-until-conditions-are-met-2026-10-04/"},
{id:"ukmto-149",date:"2 okt 2026",type:"attack",status:"confirmed",statusLabel:"UKMTO",title:"Råoljetanker träffad öster om Oman",coords:[26.05,56.55],summary:"UKMTO rapporterar att en råoljetanker träffades på babordssidan av en okänd projektil. Besättningen rapporterades säker och ingen miljöpåverkan var känd.",impact:"Håller war-risk och oviljan att erbjuda tonnage uppe, men ökar samtidigt fysisk risk för fartyg i området.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$87.28","h24":"Ingen handel 3 okt"},source:"https://www.ukmto.org/"},
{id:"ukmto-148",date:"2 okt 2026",type:"attack",status:"confirmed",statusLabel:"UKMTO",title:"Tanker träffad under utgående Hormuzpassage",coords:[26.35,56.35],summary:"En tanker träffades av en okänd projektil under utgående passage. Mindre brand och blackout rapporterades; myndigheter utreder.",impact:"Ytterligare belägg för återkommande fysisk risk mitt i återhämtande exportflöden.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$87.28","h24":"Ingen handel 3 okt"},source:"https://www.ukmto.org/"},
{id:"ukmto-147",date:"1 okt 2026",type:"attack",status:"confirmed",statusLabel:"UKMTO",title:"Tanker träffad – brand ombord",coords:[26.42,56.45],summary:"UKMTO mottog tredjepartsrapport om tanker träffad av okänd projektil under transit genom Hormuz, med brand som följd. Besättningen rapporterades säker.",impact:"Stödjer fortsatt hög riskpremie och begränsad effektiv fartygstillgång.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$85.74","h24":"$87.28 vid nästa stängning (+1.80%)"},source:"https://www.ukmto.org/"},
{id:"outflow",date:"1 okt 2026",type:"shipping",status:"reported",statusLabel:"MARKNADSDATA",title:"Hormuz crude outflow omkring 12,4 miljoner fat",coords:[25.95,56.8],summary:"Windward rapporterar med Vortexa-data 12,4 miljoner fat i crude outflow den 1 oktober och en kraftig ökning av STS-relaterade volymer.",impact:"Mer faktisk last samtidigt som logistiken är ineffektiv är gynnsamt för ton-mile och fartygsefterfrågan.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$85.74","h24":"$87.28 vid nästa stängning (+1.80%)"},source:"https://insights.windward.ai/"},
{id:"iraq-vlcc",publishedAt:"2026-10-03T12:00:00+02:00",date:"3 okt 2026",type:"shipping",status:"confirmed",statusLabel:"REUTERS",title:"Irak transporterar 2 miljoner fat genom Hormuz",coords:[29.68,48.82],summary:"Iraks statliga tankerbolag uppger att 2 miljoner fat råolja transporterats genom sundet på en VLCC – bolagets första operation av detta slag på årtionden.",impact:"Visar att stora VLCC-laster faktiskt kan röra sig trots säkerhetsläget; bra för fraktefterfrågan.",stock:{"at":"$87.28 (senaste avslut 2 okt)","h1":"Ingen handel","close":"$87.28 (2 okt)","h24":"$87.28 • ingen handel"},source:"https://www.reuters.com/business/energy/iraq-says-it-transported-2-million-barrels-crude-through-strait-hormuz-2026-10-03/"},
{id:"yanbu",date:"1–4 okt 2026",type:"shipping",status:"reported",statusLabel:"ANALYS",title:"Yanbu-terminaler fortsatt i bruk efter rapporterad incident",coords:[23.96,38.18],summary:"Windward uppger att terminalaktivitet syns efter en rapporterad projektilincident den 1 oktober; Saudiarabien hade inte bekräftat incidenten i deras rapport.",impact:"Fungerande Red Sea-export ger alternativ till Hormuz, men attacker eller avbrott här skulle binda ännu mer tonnage.",stock:{"at":"Ej fastställbar • datumintervall","h1":"—","close":"—","h24":"—"},source:"https://insights.windward.ai/"},
{id:"vlcc-market",date:"2 okt 2026",type:"market",status:"confirmed",statusLabel:"MARKNAD",title:"VLCC spotmarknad till nya rekord efter attacker",coords:[25.15,56.35],summary:"TradeWinds rapporterar att VLCC-spotmarknaden stigit till nya rekord efter den senaste attackvågen och att Hormuztransiter fallit.",impact:"Direkt positivt för potentiell spot-TCE på Okeanis VLCC-flotta, med motsvarande högre operativ risk.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$87.28","h24":"Ingen handel 3 okt"},source:"https://services.tradewindsnews.com/tankers"},
{id:"suezmax-market",date:"2 okt 2026",type:"market",status:"confirmed",statusLabel:"MARKNAD",title:"Suezmaxmarknaden pressad till gränsen",coords:[20.0,45.0],summary:"TradeWinds rapporterar att vissa Suezmax-rater överstiger VLCC-intjäning i en marknad beskriven som stretched to its limits.",impact:"Särskilt relevant eftersom Okeanis har både VLCC- och Suezmaxexponering.",stock:{"at":"Minutdata saknas","h1":"Minutdata saknas","close":"$87.28","h24":"Ingen handel 3 okt"},source:"https://services.tradewindsnews.com/tankers"}
];